language: C

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7

script: make CC=gcc-7 debug

git:
    depth: 1
    quiet: true

notifications:
    email:
        on_success: never
        on_failure: always
